name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-66597a7182e319000195d626-725da6eb0bb25e749aa251ee36b5cc4e26
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Petstore.json" --integration-id "163879-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 2542b7a9-acd1-461e-8330-4cf5f5b4fa42 --integration-id 163879
